Repository hash-define-organization/Hash-Whiteboard, pull requests merged in 2022-03, with the labels that each got.

#3 Changed Readme.md file
  README.md
Labels: documentation, GSSoC'22, Level-1

#24 chore: Correct link to Contributing Guidelines file
  README.md
Labels: GSSoC'22, Level-2

#16 fixed zoom issue
  src/Assets/Icons/Eraser.svg
  src/Components/Main/Main.js
Labels: GSSoC'22, Under-review

#23 Added yarn usage in readme
  README.md
Labels: GSSoC'22

#25 Preloader Functionality Added
  package-lock.json
  public/hashdefine.jfif
  src/App.js
  src/Components/Preloader/Preloader.jsx
  src/Components/Preloader/Preloader.scss
Labels: GSSoC'22, Level-3

#35 Changed header font family
  src/App.scss
Labels: GSSoC'22, Level-1

#41 Update Readme with some important points
  Contributing.md
  README.md
Labels: documentation, GSSoC'22, Level-1

#30 Eraser thickness Pop Up #27
  package-lock.json
  public/cursors/Eraser.svg
  src/Components/Eraser/Eraser.js
  src/Components/Main/Main.js
  src/Components/Main/Main.scss
  src/Components/SketchField/SketchField.jsx
Labels: GSSoC'22, Level-3, Under-review
